### ISSUE TITLE
Mails won't sync when system connects to a different AP when N1 is on.

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#1146]
Right off the bat, I am not sure if this is a platform dependent issue or not. This is a definitely reproducible bug on my machine.

Version: 0.3.45, compiled from 3b5880e 

Mails wouldn't sync after system resumes from sleep. It happened about 7 out of 8 times over last 3 days. One more condition that changes while system is in sleep is that it moves between my work and home networks. Only way I could get sync back up is by restarting N1.

Update:
Check [https://github.com/nylas/N1/issues/1146#issuecomment-186144213](https://github.com/nylas/N1/issues/1146#issuecomment-186144213) for exact reproducible steps

**Comment by bashok001** [comment]
Hello @mbilker and Nylas Team, this became a daily issue for me. Any updates on whether you can replicate it or not. If not, we can discuss and find the root.

**Comment by mbilker** [comment]
@bashok001 I can not replicate in on my Linux laptop. It appears Chrome and N1 (using Chromium) receive events via D-Bus or poll to see if the network interface is up. It then reopens the Delta Stream connection. Also, NetworkManager disconnects from its connections when the computer is put to sleep.

Sorry if I already asked for this, what OS are you using with N1?

**Comment by bashok001** [comment]
Hi @mbilker , I am using Arch Linux. So, the problem comes when following this sequence. 

System Boot -> Connect to wifi A -> Start n1 -> Sleep -> Resume -> Connect to Wifi B

Now, nylas is still running but sync wont be working anymore. So, I had to quit n1 and start it back again.

**Comment by mbilker** [comment]
Hmm. This is a weird issue. I do not know what is causing this to happen behind the scenes. What does the Activity Window show after waking the computer up from sleep? Are the Delta Stream lights green?

**Comment by bashok001** [comment]
![screenshot from 2016-02-09 18-48-00](https://cloud.githubusercontent.com/assets/2344626/12934899/d9636c54-cf5f-11e5-8c2d-6d7e650eef79.png)

Excuse my poor skills with that image.

The lights are as shown in the image. They are alternatively green and status is shown as "Retrying"

**Comment by koterpillar** [comment]
This is happening for me on `v0.4.5-b0ec335`. The Activity window screenshot attached. The "Delta Streaming" light sometimes goes gray and then back to green.
![2016-02-11 22-30-06](https://cloud.githubusercontent.com/assets/140276/12975407/70cf2d16-d10f-11e5-9731-4e2b8b0b2323.png)

The time shown in the requests is from the previous Wi-Fi network, before the computer went to sleep.

I am also using Arch Linux, with Network Manager. Running `nm-online` exits immediately with success, so Network Manager agrees the computer is online.

**Comment by bashok001** [comment]
So, @koterpillar , your mails are syncing after computer resumes from sleep and connects to different wifi?

**Comment by koterpillar** [comment]
They are not, I still only see the emails from before the computer went to sleep.

**Comment by bashok001** [comment]
Awesome.... So, this is reproducible.

**Comment by mbilker** [comment]
I think http://electron.atom.io/docs/v0.36.7/api/power-monitor/ needs to be used to monitor if the computer goes to sleep and restart all pending tasks and reinitialize the Delta Streams.

**Comment by bashok001** [comment]
I found an interesting thing. Yesterday, I didn't restart N1 at home. When I reached work today, sync started working again. Can you check that, @koterpillar ?

**Comment by mbilker** [comment]
Going along with that, I closed my computer and reopened it after it went to
sleep. After the computer reconnected to WiFi, N1 reconnected to the hosted
Sync Engine and synced the emails I missed.

> On Feb 18 2016, at 5:32 pm, Ashok Bommisetti
&lt;notifications@github.com&gt; wrote:  

>

> I found an interesting thing. Yesterday, I didn't restart N1 at home. When I
reached work today, sync started working again. Can you check that,
[@koterpillar](https://github.com/koterpillar) ?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1146#issuecomment-185955131).![](https://github.com/notifications/bea
con/ABNTbfLvNPj9u-7_7tqvlwwcUseNPLiOks5plj3tgaJpZM4HNzY0.gif)

**Comment by koterpillar** [comment]
@bashok001 so you're saying if you:

- Start N1 on network A; sleep
- Resume on network B; ignore non-syncing N1; sleep
- Resume on network A;

then N1 will start syncing again? So the bug is limited to "resume on a different network"?

**Comment by bashok001** [comment]
@mbilker , if its same network, even my sync is working.
@koterpillar As wierd as it is... It looks like it. Can you try?

**Comment by koterpillar** [comment]
I don't have geographically separated networks at the moment, so this is what I've done:

* Start N1 while connected to network A
* Switch to network B via NetworkManager
* Send myself an email, wait for 10 minutes - email not received
* Switch to network A via NetworkManager
* Email received within 5 seconds.

A and B do not share the same external IP, one is a mobile network shared via the phone and another one is a cable line.

This suggests that sleep/resume might not be a factor at all.

**Comment by bashok001** [comment]
@koterpillar That is a very reproducible experiment. I repeated it and saw the same result.

**Comment by mbilker** [comment]
@bashok001 I am on Linux as well with NetworkManager. I will attempt to reproduce later.

**Comment by bashok001** [comment]
This is a problem that still exists in 0.4.19 - d41e72c . This means I can't have N1 open across multiple Wifi sessions. Any progress or exploration about this? @bengotow ?

**Comment by mbilker** [comment]
This is really strange. I was able to use an N1 session between multiple networks. I used my phone's hotspot, home internet, and then VPN off of my home internet (ensured it went through VPN).

**Comment by bengotow** [comment]
This should be fixed in 0.4.33. N1 will detect that it's socket has been broken much faster (~15 seconds) and will reconnect. There will also be a "you are offline" notice briefly when the connection is down.

**Comment by koterpillar** [comment]
This is still not fixed in 0.4.40. Although the connection works fine, a "Nylas N1 isn't able to reach api.nylas.com" message is displayed, and the mails are not synchronized.

Possible duplicate: #2243.

**Comment by bashok001** [comment]
Still not fixed in 0.4.40

**Comment by saligrama** [comment]
I opened #2243 which was referenced here, still does not seem to be fixed. It looks like the same issue occurs with Spotify (unable to connect to the internet when switching networks), also on Arch x64.
