### ISSUE TITLE
Drafts suddenly appear as sent, but are not actually sent

### ISSUE THREAD

**Issue by riversy** [nylas/N1#1175]
Does somebody met that? 
N1 sends incomplete email then I type email in the embedded editor and switch to other window. 
It's very annoying :D 
Is it possible to fix that?

My system is Ubuntu Gnome 15.10 x64

**Comment by mbilker** [comment]
Thanks for the report @riversy. Which version of N1 are you running? This issue should be fixed in the most recent version.

**Comment by riversy** [comment]
I'm running N1 0.3.45. Has been installed via .deb package.

**Comment by bengotow** [comment]
I think this issue should be addressed in the latest beta 0.4.0. That said, it sounds like you're typing the email in one window and sending it from another window? That's definitely not something we've tried...

**Comment by riversy** [comment]
No, it happens then I typing in the thread. It looks like some action does trigger "Send action". But I'm not sure. I've prepared a short video - https://youtu.be/TVSvQOytk6Y 
It happens on 0.53. It sends email without any action. But I couldn't reproduce that again. Only one time.

**Comment by emorikawa** [comment]
@riversy Wow. Thank you for the video! That is very weird. I also saw in your video the draft failing to delete. I was wondering what plugins you have installed? We'll take a look at this.

**Comment by riversy** [comment]
@emorikawa Yes, I've installed quick replies. Might it be a reason?

**Comment by riversy** [comment]
@emorikawa Heads up! I've disabled the plugin, but issue still here. Hope it help.

**Comment by joshvickerson** [comment]
This just happened to me as well, with version 0.4.5-b0ec335 on OS X 10.11.3.

I'm not sure what triggered the send, as I had just finished typing a sentence. Right before that (maybe 2 or 3 seconds) my inbox had finished syncing. Is it possibly a bug in syncing that causes a draft to send?

**Comment by joshvickerson** [comment]
Actually, on closer inspection in my case it doesn't appear as though the mail is actually sent, but it does get the 'sent' tag. The email appears as a sent item in N1, but the email is also still a draft. In gmail, the email also appears as a draft, but is also shown in sent mail. When viewed in sent mail, gmail will let me edit the email and still send it.

So, it's getting the sent tag, but not actually sending, as far as I can tell.

**Comment by mirisuzanne** [comment]
I think this may be the same issue I'm seeing. If I work on a draft long enough, it suddenly (sometimes in the middle of typing) becomes in-editable, as though it has been sent. As far as I can tell, it never actually sends, but I have to copy-paste what I was working on and start a new draft. This has happened several times, only since updating to the latest version 0.4.5-b0ec335.

Steps to reproduce: work on a draft reply for a long time, using the embedded editor.

**Comment by natarius** [comment]
@mirisuzanne That might be the pattern! It also only happens to me on longer emails

**Comment by lmerriam** [comment]
Getting this too, on OSX and v0.4.5-b0ec335. Seems to happen during autosave or something--just randomly while the draft is open. The email does not appear in my sent mail in Nylas or Gmail, it does appear as a draft in Gmail, but the Nylas inbox thinks it was sent.

**Comment by eldarkg** [comment]
+1. Nylas mark mail how sended but nothing send

**Comment by bram96** [comment]
I have this issue also when working on short mails, when I click another mail and when I come back it is marked as sent. When I look in the Gmail webapp it is still there as concept.

Using Ubuntu 14.04, Nylas N1 0.4.9-575c-091

**Comment by geekgonecrazy** [comment]
This is happening to me as well.  Latest version on windows.

It seem to happen after I stopped typing for a few minutes.   Its happened maybe 10 times today?  Never had it happen before now.

I noticed that it briefly added the trash label to it.  Then after a while that label went away.

In gmail they do show as drafts... but even after several restarts of Nylas it still thinks these are sent..

**Comment by bengotow** [comment]
Hi folks—sorry for the hassle. I've been debugging this all day, and we've identified two issues with drafts which often appear together and I think are both being reported here. We'll be fixing all of them in the next release or two. Here's a quick recap:

- We autosave drafts as you compose them, and there's a strange sync edge-case where the "draft" flag is removed from the message while you're still working on it. This causes it to become immediately un-editable. (N1 is built with React so the whole UI updates declaratively based on the underlying data. This is very annoying sometimes.) This is a backend issue and will be fixed soon.

- If you compose a draft in response to message A and send it, and then compose a new draft also in response to message A, the draft appears /at the same index/ in the message list and incorrectly appears in the "sending" state. A fix for this is in review and will land on master tomorrow. 

Note that neither of these cases cause duplicate or premature emails to actually send. It just looks like they are (which, don't get me wrong, is still quite bad.) Stay tuned.

**Comment by geekgonecrazy** [comment]
@bengotow thanks for the update!

I've experienced both issues, and look forward to the fix. 

Keep up the awesome work! :+1:

**Comment by mirisuzanne** [comment]
That all fits my experience, thanks for the update!

**Comment by Nevel** [comment]
I experienced the same using "Linux Mint 17.3 Rosa".
In my case, none of the drafts get sent.
I just have to start over again :).

**Comment by jstejada** [comment]
Hey! This should be fully resolved in 0.4.14. We've temporarily disabled server syncback of drafts to IMAP and Gmail while we work on a few edge case issues. Thanks -
