### ISSUE TITLE
Reply message is sent from a different account and fails to send

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1235]
I received a message at my mark@decisionsciences account (see below) but when I used the reply function, it replied from mark.bao@columbia. Also, the message is failing to send (spins forever), and there seems to be a 404 error. When I quit and restart, the message is no longer there. What I did was to reply, delete my signature, type my message, and send.

<img width="429" alt="screenshot_2_8_16__10_31_am" src="https://cloud.githubusercontent.com/assets/27594/12889967/698e2e0c-ce4f-11e5-8d9a-09854d4c6c9b.png">

Nylas N1 Version 0.4.5-b0ec335 (0.4.5-b0ec335) (Binary version)
OS X El Capitan 10.11.3 (15D21)

**Comment by mbilker** [comment]
The error to receive the raw message occurs on sent messages from N1, but not for messages received.

**Comment by markbao** [comment]
^ Hmm... So is that error relevant? I am sending.

**Comment by mbilker** [comment]
The error is on the Sync Engine side. Check the _Queue_Length_ tab and the task for the sent message and check `SendDraftTask` for the email used for sending the message.

**Comment by markbao** [comment]
Actually, it turns out these messages sent, but they're not on the original thread... I sent three of them and they are in my All Mail. They are all sent from my mark.bao@columbia account.

**Comment by markbao** [comment]
If it helps any, I'm using unified inbox, with this setting:

![image](https://cloud.githubusercontent.com/assets/27594/12894910/b91f8728-ce67-11e5-8155-96639d8dc3f6.png)

Accidentally sent a client a reply email from my Columbia address... this seems like a big issue.

**Comment by markbao** [comment]
Oh, and something else I noticed was that while I was composing my message, after a minute or two the quick-reply just disappeared. I found my message in Drafts. Maybe this is related.

**Comment by bengotow** [comment]
Hi @markbao — thanks for filing this. I'm looking at the relevant code right now. Is the address that you received this email from (the `mark@decisionsciences` email) configured as an account or as an alias on one of your accounts? Is the issue that it replied using the wrong alias, or the wrong account?

**Comment by markbao** [comment]
Thanks for the follow-up @bengotow. Wrong account. Here's the structure of my accounts:

- mark@markbao
- mtb2144@columbia
  - alias: mark.bao@columbia <— used to reply
- mark@decisionsciences <— received email here

**Comment by markbao** [comment]
Another update while playing around with this: I deleted the alias:

<img width="838" alt="screenshot_2_8_16__2_18_pm" src="https://cloud.githubusercontent.com/assets/27594/12896241/f1f5b9a8-ce6e-11e5-84c8-369f3130c287.png">

And then I tried reproducing the related issue in #1237 and it's *still* using the alias:

<img width="495" alt="screenshot_2_8_16__2_19_pm" src="https://cloud.githubusercontent.com/assets/27594/12896269/0fbfc334-ce6f-11e5-984d-27b8ca382d3a.png">

Even though it's not in the list:

<img width="532" alt="screenshot_2_8_16__2_21_pm" src="https://cloud.githubusercontent.com/assets/27594/12896304/45a9dffc-ce6f-11e5-97fa-b89e563af2c8.png">

Tried restarting; issue persisted.

**Comment by mbilker** [comment]
I found out that one email sent to me by @w4 from some time ago had the `From: ` part as another email of his, but it sent via a separate mail-server. I have attached the raw message for diagnosis.

[message_original.txt](https://github.com/nylas/N1/files/122181/message_original.txt)

**Comment by lleger** [comment]
I'm having the same issue as Mark. I replied to an email sent to my work account, but it was actually sent from a personal account.

**Comment by jstejada** [comment]
hey @markbao, I have a few questions regarding your issue:

1. Did you configure a default alias?
2. When you said it sent the email incorrectly from the alias, do you mean that the alias was selected as the `From` field in the composer. Or that having selected the correct account, it sent it incorrectly from the alias?
3. In the third case, you opened a new composer window after deleting the alias, and it still showed the incorrect `From:` address, correct?

**Comment by markbao** [comment]
1. I configured one alias, `mark.bao@columbia`, under my `mtb2144@columbia` email address. It was automatically selected as the default alias for `mtb2144@columbia` account.

2. Case 1: quick reply send. I'd compose a reply to a message sent to `mark@decisionsciences` or `mark@markbao` and it would send from `mark.bao@columbia`. I didn't see the `From:` field. — Case 2: same as above, start quick reply, but it disappears as in #1237. In this case, the message would be in my Drafts folder. When opened, the message displays the *wrong* `From:` field and that's the field that it sends from when I hit send.

3. Not exactly but basically the gist of it. The only difference between my experience and your explanation was that I didn't open a new composer window but rather replied to a message. Specifically, I first deleted the alias. Then I went and composed a new reply. Soon enough, it disappeared and I went to Drafts to find it and open it. When opening it, I found that the `From:` field continued to display the alias address, despite having deleted it and despite it not being in the dropdown.

@lleger feel free to chime in if you have any other observations.

**Comment by lleger** [comment]
My experience exactly matches that of Mark's, including the issue he described in #1237. I have 4 accounts — one of them has a default alias. The default alias was indeed the wrong address. It happened for both replies and new emails.

**Comment by lleger** [comment]
Also I should point out that the signature seemed to be correct. I didn't notice this bug until much later in the day because the signature was correct for the email I *should* have been sending from. For example, I replied from `logan -@- newaperio` and the signature was the one I had configured for my NewAperio account — correct. But it sent from `logan -@- loganleger` — incorrect.

**Comment by jstejada** [comment]
great, thanks for the additional details.

**Comment by markbao** [comment]
Not to be *that guy* but this continues to be an issue as of ab527ab3a5bbfe3346590a241162ae3405d0bc56. New composer window shows non-existent account; added back the alias in settings and still the same behavior, removed alias and it still appears.

Some interesting compose behavior that might be useful. When I switch to [X] account in the sidebar, and open a compose window, it uses [Y] account for the From field:

| When I switch to...   | Composer From: shows... |
|-----------------------|-------------------------|
| mark@markbao          | mark.bao@columbia       |
| mtb2144@columbia      | **mtb2144@columbia**        |
| mark@decisionsciences | mark.bao@columbia       |
| mark@citizenreach     | mark.bao@columbia       |

**Comment by jstejada** [comment]
hey @markbao, @lleger, I haven't been able to reproduce your issue successfully. So it seems that it is always attempting to send from your alias, regardless of what account the alias is tied to, and even if you delete the alias, correct? 

Is this behavior consistent, or does it happen on occasion? Do you have any additional details on how you got to this state? E.g. in what order did you add the accounts? Did you change the setting for `Send new messages from` at some point? Did you change the setting for `Default alias` at some point? Was the alias already configured before the 0.4.5-b0ec335 update? Do you still have the alias? If you take a look at `~/.nylas/config.cson`, what is the value for the field `default_alias` inside each of your accounts?

Thanks!

**Comment by markbao** [comment]
> So it seems that it is always attempting to send from your alias, regardless of what account the alias is tied to, and even if you delete the alias, correct?

It is always attempting to send from the alias, regardless of whether the email that I am replying to is actually sent to that alias. So replying to an email from mark@markbao will still be replied from from mark.bao@columbia. Even if the alias is deleted. **Except when I get an email to mtb2144@columbia, and then the composer sets the From: correctly to mtb2144@columbia.**

Also, new message window has similar behavior, see table above.

> Is this behavior consistent, or does it happen on occasion?

100% consistent. I haven't found an instance where it doesn't happen.

> Do you have any additional details on how you got to this state? E.g. in what order did you add the accounts?

To the best of my knowledge: added mark@markbao, then mtb2144@columbia, then mark@decisionsciences. Then, Alias support came out and I added mark.bao@columbia as an alias to mtb2144@columbia and then added mark@citizenreach since I was making N1 my main client.

>  Did you change the setting for Send new messages from at some point? Did you change the setting for Default alias at some point? 

Never changed these explicitly. I played around with these a few days ago after updating to master at ab527ab.

> Was the alias already configured before the 0.4.5-b0ec335 update?

Yes, they were configured before Unified Inbox.

> Do you still have the alias?

No.

> If you take a look at ~/.nylas/config.cson, what is the value for the field default_alias inside each of your accounts?

This seems to be the jackpot. Here's the relevant part of my `config.cson` with sensitive info scrubbed.

```
  nylas:
    accounts: [
      {
        client_id: "XXXX"
        server_id: "XXXX"
        object: "account"
        account_id: "XXXX"
        name: "Mark Bao"
        provider: "gmail"
        email_address: "mark@markbao"
        organization_unit: "label"
        label: "Mark Bao"
        aliases: []
        default_alias: "Mark T Bao <mark.bao@columbia>"
        id: "XXXX"
      }
      {
        client_id: "XXXX"
        server_id: "XXXX"
        object: "account"
        account_id: "XXXX"
        name: "Mark T Bao"
        provider: "gmail"
        email_address: "mtb2144@columbia"
        organization_unit: "label"
        label: "Columbia"
        aliases: []
        default_alias: ""
        id: "XXXX"
      }
      {
        client_id: "XXXX"
        server_id: "XXXX"
        object: "account"
        account_id: "XXXX"
        name: "Mark Bao"
        provider: "gmail"
        email_address: "mark@decisionsciences"
        organization_unit: "label"
        label: "CDS"
        aliases: []
        default_alias: "Mark T Bao <mark.bao@columbia>"
        id: "XXXX"
      }
      {
        client_id: "XXXX"
        server_id: "XXXX"
        object: "account"
        account_id: "XXXX"
        name: "Mark Bao"
        provider: "gmail"
        email_address: "mark@citizenreach"
        organization_unit: "label"
        label: "CitizenReach"
        aliases: []
        default_alias: "Mark T Bao <mark.bao@columbia>"
        id: "XXXX"
      }
    ]
```

**Comment by markbao** [comment]
Let me know if you'd like me to strike `default_alias` and see what happens.

**Comment by jstejada** [comment]
awesome thanks! yes the problem is definitely in `config.cson` -- somehow `default_alias` was incorrectly saved to all accounts instead of the one you selected, and somehow that happened when you updated to unified inbox. If you remove `default_alias` in your `config.cson` it will probably work, but I'm curious as to how it got to that state in the first place. Before removing that field in config.cson, what's the value you see for Default Alias for any of those accounts inside `Preferences -> Accounts`

**Comment by markbao** [comment]
None of them have any default aliases. All four screens look like:

<img width="822" alt="screenshot_2_15_16__10_24_pm" src="https://cloud.githubusercontent.com/assets/27594/13066358/fa7a9ad4-d432-11e5-9363-57427f442ad8.png">

**Comment by markbao** [comment]
After removing the entire `default_alias` line, things are now working correctly. Now let me see if I can get this to reproduce.

**Comment by markbao** [comment]
Can't reproduce. After removing the `default_alias`, aliases are working correctly.

**Comment by jstejada** [comment]
Ok, thanks @markbao! This error that saved incorrect default aliases for other accounts might have been present in a previous version, but without being able to reproduce I will close this issue for now. @lleger , let mw know if this works for you as well. 
Feel free to reopen if the issue comes up again.

**Comment by markbao** [comment]
Thanks for your help @jstejada! I'll let you know if I see anything else.

**Comment by lleger** [comment]
Deleting `default_alias` from my `config.cson` seemed to work. I'll continue to monitor and let you know if that changes.

**Comment by jstejada** [comment]
hey @markbao @lleger , I was able to reproduce the bug. It is fixed with https://github.com/nylas/N1/commit/7ca04c579e8c6cbf16195743416e213fc58eca20 and it will be available in an upcoming release

**Comment by mbilker** [comment]
@jstejada This may just be personal preference, but is there any benefit to `Object.assign({}, obj1, obj2)` versus `_.extend({}, obj1, obj2)`?

**Comment by markbao** [comment]
Great to hear, thanks Juan!

**Comment by mscottford** [comment]
@jstejada Manually removing the default alias from `config.cson` got me around this issue as well. But it was still happening for me even after your fix went in. And taking a peek, it looks like that fix will just prevent the issue from happening to anyone else in the future.

I'm not sure how wide spread this issue is. Would it be worth having the `config.cson` checked for inconsistencies? This one should be pretty easy to check for, because the value in `default_alias` won't exist in the `aliases` array for the accounts that the default_alias should be removed from.
