### ISSUE TITLE
"Launch on system start" not available on Linux

### ISSUE THREAD

**Issue by brittyazel** [nylas/N1#1251]
I do not know if this was an oversight, by design, or a technical limitation, but the new "launch on system startup" option found in the Windows builds is not present. Instead there is the option "show icon in menu bar" which is not found under Windows.

Is it possible to add this feature? I would love for N1 to start minimized when I startup my system

**Comment by mbilker** [comment]
Thanks for the request @brittyazel. It is a technical limitation on the Linux platform. There are many ways to handle launching N1 at startup on Linux. This includes `.xinitrc`, XDG autostart, WM-specific autostart, and systemd user sessions.

What I do not know is if there is a command line option to start N1 minimized. If there is such an option, then it would be as simple to create an entry in your method to run at startup minimized using that option.

I use Arch Linux as my daily driver on both my desktop and laptop. I understand that people have different needs under the Linux ecosystem. I use the `i3` tiling window manager, and I would run N` at startup through an `exec` call in my `~/.config/i3/config` because that is the easiest and most central place to manage processes at startup after the whole X11 display started up as `systemd` user sessions are a little bit finnicky.

**Comment by brittyazel** [comment]
I too use Arch Linux as my daily driver. I know that some apps can start in the background, as I used to use Geary (before it was abandoned) and it would start in the background. And dropbox does the same. Now whether or not it is an app-specific thing or a Linux desktop thing, I have no clue :-/

**Comment by mbilker** [comment]
Yay another Arch Linux user here. That sucks about Geary. N1 has the ability to start background, and it is [available](https://github.com/nylas/N1/blob/918090a4e1105b99b323a59882c33c55a3c029fc/src/system-start-service.es6#L67) through the `--background` command line option. Have fun!

On another note, if you have plugin issues, please run `sudo chmod 755 /usr/share/nylas/resources/app/apm/bin/node /usr/share/nylas/resources/app/apm/bin/apm`.

**Comment by brittyazel** [comment]
You are correct, nylas --background did result in it opening up in the background. That being said, the way Gnome has programs launch on start is by putting a .desktop file in ./config/autostart . Which is the way that Geary did it, clicking the toggle just dropped a .desktop file in the autostart folder with the --hidden command appended to the exec line. It seems such a solution would work beautifully for all Gnome-based desktops. I believe KDE also has an autostart folder ( ./kde/autostart I believe).

**Comment by brittyazel** [comment]
Actually I believe kde will also look in the ~/.config/autostart as well for .desktop files. Is it possible to go the route of Geary, and add the checkbox in, which really just drops a copy of the .desktop file into /.config/autostart with the --hidden appended to it? It seems simple enough and should work for Ubuntu/Gnome/Kde and those variants within

**Comment by mbilker** [comment]
@brittyazel It is possible to go the route and add support for the checkbox, but it is a hassle to support more than one desktop environment.

I see most Linux users here use GNOME, KDE, or i3. Geary was targeted at GNOME users, which is why that flag was present. N1 is targeted at the larger audience. I wonder what @bengotow would have to say.

**Comment by brittyazel** [comment]
Yes but I believe the same technique could be used for all Gnome and KDE desktops. They both use the same method and folder for autostarting applications. I can not speak for i3.

**Comment by brittyazel** [comment]
I could see a solution being an implementation of the checkbox, which drops the appended .desktop file into /.config/autostart, with a note to i3 users that they will need to manually add the "exec nylas --background" to their config file manually. Which shouldn't be a problem for i3 users anyway, as to be an i3 user in general means that editing config files is up your alley.

**Comment by mbilker** [comment]
@brittyazel Hmm. From my research on the awesome Arch Linux Wiki, I found that the XDG directory is the best solution for the Linux side ([source](https://wiki.archlinux.org/index.php/Desktop_entries#Autostart)).

**Comment by mbilker** [comment]
N1 could display a notification to all Linux users that they need an XDG-compliant environment (e.g. Unity, GNOME, or KDE) for launch at startup. If they need support under other environments, they need `dapper`, `dex`, or `fbautostart`.

**Comment by brittyazel** [comment]
Yes /.config/autostart is XDG compliant. 
> User-specific: $XDG_CONFIG_HOME/autostart/ (~/.config/autostart/ by default)

If the checkbox is user configurable from within the application, /etc/xdg/autostart/ is off limits unless the app is run with administrator permission, which would be terrible. Thus dropping the .desktop environment in /.config/autostart ($XDG_CONFIG_DIRS/autostart/), is the only rational option if this route is to be pursued.

**Comment by Feichtmeier** [comment]
Using Ubuntu 15.10 here.
After installing Nylas a .desktop file was put into my /usr/share/applications folder :) That is great!
When I put it in the startup applications with this line to be executed "/usr/share/nylas/nylas %U" it starts nylas at start. But not minimized. I tried your tip with the arguments --background or --hidden but sadly both did not managed to let it start in the background.
Any other command line tip how I could manage that? Thanks in advance

**Comment by mbilker** [comment]
@Feichtmeier `--background` is the argument needed to run N1 in the background. I have tested the argument and it works as intended. Does Ubuntu have a startup editor to enter this in manually?

**Comment by Feichtmeier** [comment]
Yes it has. There you can either put a full path to an executable or put a path variable like "firefox" or "plank". But if you put "nylas --background" in there nothing happens. 
When I put "/usr/share/nylas/nylas %U" which also is given in the nylas.desktop file, nylas starts at start but normally with all windows and not in the background ofc.

When you type "nylas --background" into the shell you get this response:

![image](https://cloud.githubusercontent.com/assets/15329494/13671287/4ed1a11e-e6cf-11e5-963f-e184078b52dc.png)

**Comment by mbilker** [comment]
@Feichtmeier That should have been fixed in the latest version. What version of N1 are you on? The most recent version is 0.4.10, which includes #593.

**Comment by mbilker** [comment]
Whoops. Accidentally clicked "Comment & Close Issue".

**Comment by Feichtmeier** [comment]
I am running version 0.4.10-4e3595b

The nylas installer added nylas to my ubuntu repos so I think I should always
be up to date. But still, the pictures I uploaded is from today :) So, should
I maybe reinstall nylas? Or change my OS? :P

> On Mar 10 2016, at 5:53 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Whoops. Accidentally clicked "Comment &amp; Close Issue".

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1251#issuecomment-194951584).![](https://github.com/notifications/bea
con/AOno1s9c0jJJNTsK8G1lBkFt5t8RPS1iks5psEyZgaJpZM4HWJhc.gif)

**Comment by mbilker** [comment]
@Feichtmeier That is the latest version. Hmm... I suggest reinstalling Nylas, but you do not need to remove `~/.nylas`.

**Comment by Feichtmeier** [comment]
No sadly still the same output:
frederik@akira:~$ nylas 
Can't find the Electron executable at /usr/bin/electron/electron. Be sure you have run script/bootstrap first from /usr/bin or set the ELECTRON_PATH environment variable.

**Comment by mbilker** [comment]
That is not what N1 intended. I am able to start to only the background with `nylas --background` from the command line. I assume you are using Unity since you are using Ubuntu.

**Comment by Feichtmeier** [comment]
Yes I am using Unity. So you do not have the main frame opened after system start?

**Comment by mbilker** [comment]
I am going to try rebooting and having `nylas --background` listed in `i3`'s configuration as `exec /usr/bin/nylas --background`.

My `i3` configuration is available at https://gist.github.com/mbilker/dae19ee4f1a49af4a29a

**Comment by eldarkg** [comment]
Helped me in Ubuntu 15.10:
in gnome-session-properties add entry /usr/bin/nylas --background
Nylas 0.4.14

**Comment by mbilker** [comment]
I do not have the main frame open at system start with that `i3` configuration. The tray icon does appear.

**Comment by Feichtmeier** [comment]
Well it still opens the mainframe. But maybe this has something to do with my Ubuntu installation? I don't really know. I will update to 16.04 as soon as it is officially released and I can report if this is still the case.

**Comment by Siilwyn** [comment]
I'm [working on this at the moment](https://github.com/nylas/N1/compare/master...Siilwyn:linux-launch-on-start?expand=1) and thought about how to implement this. Since in the build process there is already a `nylas.desktop` generated I think we can read that file, make a few changes to it like adding the `--background` flag and then writing to the user's XDG home directory.

What do you all think?

**Comment by brittyazel** [comment]
I think that is a great idea. I would love to be able to have nylas n1 autostart

**Comment by Siilwyn** [comment]
@brittyazel could you test the branch that's referenced in the PR?

**Comment by brittyazel** [comment]
I'm not sure how to do that exactly. I wasn't building from source before, but rather just using a prebuilt package in the AUR.

**Comment by Siilwyn** [comment]
Oh well maybe somebody else can test on Arch? @mbilker?
I've tested it on Ubuntu 14.04.

**Comment by mbilker** [comment]
@Siilwyn  I do not use a WM that supports autostart via the normal XDG way. I can test the `--background` command line option via `i3`'s configuration.

**Comment by mbilker** [comment]
@Siilwyn I see your PR now. I will test to see if it puts the `.desktop` file in the correct place.

**Comment by Siilwyn** [comment]
@mbilker it won't work, I've implemented it the XDG way. I guess we'll just wait for a reaction on the PR of one of the core developers then.

**Comment by KevinMartin** [comment]
Wouldn't integrating an existing cross-platform tool with wide support be better than creating your own?

I came across this a few days ago: https://github.com/Teamwork/node-auto-launch

**Comment by Siilwyn** [comment]
@KevinMartin if there is a good cross-platform tool to do this then maybe. But as of now, no I don't think so. The `node-auto-launch` does not have error handling, does not respect the XDG environment variables and uses a static version number (which is even spelled incorrectly).

**Comment by bengotow** [comment]
Hey folks— @Siilwyn's pull request above was merged in and shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Cheers!

**Comment by leoheck** [comment]
Is it possible to launch on system start **minimized to tray** instead of opening the window?

**Comment by parsedarweb** [comment]
> bengotow commented 
> 
> Hey folks— @Siilwyn's pull request above was merged 

This feature is no longer working! Seems it's buggy as it has been described well at #3464

**Comment by xZero707** [comment]
Although stated as fixed since 0.4.32, I can confirm this issue on snap release 1.6.3-134a0e55 and Ubuntu 19.04. 
There is no checkbox present in the app, only note that auto startup works only in XDG compliant environments. 

This works for me:
```
ln -sf /var/lib/snapd/desktop/applications/mailspring_mailspring.desktop ~/.config/autostart/mailspring.desktop
```
= Which symlinks .desktop file so it's available in user startup.

**Comment by hernandez87v** [comment]
In order to get the option for "Launch on system start" I had to remove snap package and install the deb package directly from the mailspring site.

Now I have the system tray icon and starts in background!

Im using Ubuntu 19.10
Mailspring 1.7.2

**Comment by vanushwashere** [comment]
I just added mailspring in autostart and it works well :+1: 

Kubuntu 20.04 
Mailspring 1.7.6 installed via Snap

**Comment by ipkpjersi** [comment]
I can confirm that the following command from xZero707 does work for Mailspring 1.7.8 installed via Snap:

`ln -sf /var/lib/snapd/desktop/applications/mailspring_mailspring.desktop ~/.config/autostart/mailspring.desktop`

:+1: 

It would be nice if Mailspring supported this functionality out of the box for the Snap, maybe one day, who knows.
