### ISSUE TITLE
N1 syncs emails yet can't open/view them on Fedora 23

### ISSUE THREAD

**Issue by BenSchZA** [nylas/N1#1929]
The issue is this: once I sync my G-Mail emails if I select an e-mail to view, they don't open - there is the loading symbol and nothing else. 

**System Details:**
Fedora 23
Nylas N1 V0.4.19 (installed via a number of different sources - Copr, Github RPM, website RPM, different versions)
G-Mail Account
No plug-ins installed

I can't find any related issues and have tried many fixes for other issues to see if they'll work.
**Fixes tried:**
#https://github.com/nylas/N1/issues/1399

**Error log:**
`Streaming log data to /tmp/Nylas-N1-29770.30115.log
Window load time: 830ms
GET nylas://nylas-private-fonts/fonts/Nylas-Pro-Normal.otf net::ERR_FILE_NOT_FOUND
GET nylas://nylas-private-fonts/fonts/Nylas-Pro-SemiBold.otf net::ERR_FILE_NOT_FOUND
 SCAN TABLE Category for SELECT `Category`.`data` FROM `Category`   
TypeError: Cannot read property 'format' of undefined
    at Object.module.exports.Utils.fullTimeString (/usr/lib64/nylas/src/flux/models/utils.js:73:45)
    at MessageTimestamp.render (/usr/lib64/nylas/internal_packages/message-list/lib/message-timestamp.js:45:24)
    at MessageTimestamp.render (/usr/lib64/nylas/internal_packages/message-list/lib/message-timestamp.js:3:61)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at [object Object].wrapper [as _renderValidatedComponent] (/usr/lib64/nylas/node_modules/react/lib/ReactPerf.js:70:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at [object Object].wrapper [as mountComponent] (/usr/lib64/nylas/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/usr/lib64/nylas/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/usr/lib64/nylas/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at [object Object].wrapper [as mountComponent] (/usr/lib64/nylas/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:38:35)
From previous event:
    at ModelQuery.then (/usr/lib64/nylas/src/flux/models/query.js:203:29)
    at MessageStore._fetchFromCache (/usr/lib64/nylas/src/flux/stores/message-store.js:327:20)
    at MessageStore._onApplyFocusChange (/usr/lib64/nylas/src/flux/stores/message-store.js:235:19)
    at MessageStore._onApplyFocusChange (/usr/lib64/nylas/src/flux/stores/message-store.js:3:61)
    at MessageStore._onFocusChanged (/usr/lib64/nylas/src/flux/stores/message-store.js:211:14)
    at MessageStore._onFocusChanged (/usr/lib64/nylas/src/flux/stores/message-store.js:3:61)
    at EventEmitter.eventHandler (/usr/lib64/nylas/src/flux/modules/reflux-coffee.js:206:27)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at FocusedContentStore.module.exports.Publisher.trigger (/usr/lib64/nylas/src/flux/modules/reflux-coffee.js:218:30)
    at /usr/lib64/nylas/src/flux/stores/focused-content-store.js:101:24
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
GET nylas://nylas-private-fonts/fonts/Nylas-Pro-Medium.otf net::ERR_FILE_NOT_FOUND
TypeError: Cannot read property 'format' of undefined
    at Object.module.exports.Utils.fullTimeString (/usr/lib64/nylas/src/flux/models/utils.js:73:45)
    at /usr/lib64/nylas/internal_packages/participant-profile/lib/sidebar-related-threads.js:103:66
    at Array.map (native)
    at RelatedThreads.render (/usr/lib64/nylas/internal_packages/participant-profile/lib/sidebar-related-threads.js:89:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at [object Object].wrapper [as _renderValidatedComponent] (/usr/lib64/nylas/node_modules/react/lib/ReactPerf.js:70:21)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:746:36)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].wrapper [as updateComponent] (/usr/lib64/nylas/node_modules/react/lib/ReactPerf.js:70:21)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:524:23)
    at Object.ReactReconciler.performUpdateIfNecessary (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:115:22)
    at runBatchedUpdates (/usr/lib64/nylas/node_modules/react/lib/ReactUpdates.js:151:21)
From previous event:
    at ModelQuery.then (/usr/lib64/nylas/src/flux/models/query.js:203:29)
    at FocusedContactsStore._loadCurrentParticipantThreads (/usr/lib64/nylas/src/flux/stores/focused-contacts-store.js:124:109)
    at FocusedContactsStore._onFocusContact (/usr/lib64/nylas/src/flux/stores/focused-contacts-store.js:116:21)
    at FocusedContactsStore._onFocusContact (/usr/lib64/nylas/src/flux/stores/focused-contacts-store.js:3:61)
    at FocusedContactsStore._popuateCurrentParticipants (/usr/lib64/nylas/src/flux/stores/focused-contacts-store.js:82:19)
    at FocusedContactsStore.<anonymous> (/usr/lib64/nylas/src/flux/stores/focused-contacts-store.js:67:28)
    at later (/usr/lib64/nylas/node_modules/underscore/underscore.js:828:25)
TypeError: Cannot read property '_currentElement' of null
    at Object.ReactReconciler.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:55)
    at [object Object].ReactCompositeComponentMixin.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:279)
    at Object.ReactReconciler.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:56)
    at Object.ReactChildReconciler.unmountChildren (/usr/lib64/nylas/node_modules/react/lib/ReactChildReconciler.js:119)
    at ReactDOMComponent.ReactMultiChild.Mixin.unmountChildren (/usr/lib64/nylas/node_modules/react/lib/ReactMultiChild.js:329)
    at ReactDOMComponent.Mixin.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactDOMComponent.js:481)
    at Object.ReactReconciler.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:56)
    at [object Object].ReactCompositeComponentMixin.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:279)
    at Object.ReactReconciler.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:56)
    at Object.ReactChildReconciler.unmountChildren (/usr/lib64/nylas/node_modules/react/lib/ReactChildReconciler.js:119)
    at ReactDOMComponent.ReactMultiChild.Mixin.unmountChildren (/usr/lib64/nylas/node_modules/react/lib/ReactMultiChild.js:329)
    at ReactDOMComponent.Mixin.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactDOMComponent.js:481)
    at Object.ReactReconciler.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:56)
    at [object Object].ReactCompositeComponentMixin.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactCompositeComponent.js:279)
    at Object.ReactReconciler.unmountComponent (/usr/lib64/nylas/node_modules/react/lib/ReactReconciler.js:56)
    at Object.ReactChildReconciler.unmountChildren (/usr/lib64/nylas/node_modules/react/lib/ReactChildReconciler.js:119)
Uncaught TypeError: Cannot read property '_currentElement' of null`

**Comment by bengotow** [comment]
Looks like the relevant bit is:

```
 TypeError: Cannot read property 'format' of undefined at Object.module.exports.Utils.fullTimeString (/usr/lib64/nylas/src/flux/models/utils.js:73:45) at MessageTimestamp.render (/usr/lib64/nylas/internal_packages/message-list/lib/message-timestamp.js:45:24) at MessageTimestamp.render (/usr/lib64/nylas/internal_packages/message-list/lib/message-timestamp.js:3:61) at [object 
```

**Comment by bengotow** [comment]
Hi @BenSchZA — does this happen for all threads you try to view, or just some of them? It's pretty strange that it's finding threads with NULL "last message received timestamps". I've committed 66e86d8f80af7caad7f6efc68310f3a31c918fdc which will downgrade this to "weird" and allow you to view threads, but it's still pretty strange.

**Comment by BenSchZA** [comment]
Hi @bengotow - It happens for all threads I try view. Thanks for the fix, hopefully it works - I have a feeling it is a deeper issue, but I will try a few more things (building from source etc.).

**Comment by bengotow** [comment]
Hey! Thanks—I'm going to go ahead and close this since the patch is shipping in 0.4.25 today, but let me know if you continue to run into issues and we can dig a bit deeper.

**Comment by BenSchZA** [comment]
I've just updated to 0.4.25, still getting the same issue building from Github repo - I've attached the logs.

[-1460532086758.txt](https://github.com/nylas/N1/files/216532/-1460532086758.txt)
[-1460532086761.txt](https://github.com/nylas/N1/files/216533/-1460532086761.txt)

**Comment by biji** [comment]
same here.. still get 
```
TypeError: Cannot read property 'format' of undefined
    at Object.module.exports.Utils.fullTimeString (
```

**Comment by vanhonit** [comment]
Same here. I tried latest git 0.4.38.

**Comment by vanhonit** [comment]
Hi all,
I have fixed the problem on fedora and build package rpm. Here the package [https://github.com/vanhonit/N1/blob/master/nylas-0.4.38-0.1.fc22.x86_64.rpm] for who want.

**Comment by BenSchZA** [comment]
Finally! I works. Thanks Hon.

On Tue, May 17, 2016 at 11:25 AM, Hon Nguyen <notifications@github.com>
wrote:

> Hi all,
> I have fixed the problem on fedora and build package rpm. Here the package
> [
> https://github.com/vanhonit/N1/blob/master/nylas-0.4.38-0.1.fc22.x86_64.rpm]
> for who want.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nylas/N1/issues/1929#issuecomment-219665164>
>



-- 
Benjamin Scholtz
Mechatronic Engineering Student
(021) 671 9500
(076) 338 1243
bscholtz.bds@gmail.com
