### ISSUE TITLE
Nylas creating hundreds of unique duplicate drafts for one email / Drafts duplicating and copying themselves

### ISSUE THREAD

**Issue by stephen-puiszis** [nylas/N1#2237]
One email, hundreds of drafts being created (redacted image)

- Gmail
- Version 0.4.38-27d21d1 (0.4.38-27d21d1)

**Comment by yamadapc** [comment]
I think I've the same issue. They can't be deleted.

<img width="1786" alt="screenshot 2016-05-20 10 56 31" src="https://cloud.githubusercontent.com/assets/3923654/15429983/b180f396-1e79-11e6-8b41-51fbf96308fc.png">

**Comment by csampersand** [comment]
Having the same problem.

**Comment by dubstrike** [comment]
Same here.
- Gmail
- 0.4.40-85cf726

**Comment by danielbayley** [comment]
+1. This has been driving me nuts ever since I installed N1! I have to switch back to Apple mail to actually compose emails.

* iCloud
* 0.4.40-85cf726

**Comment by joaojusto** [comment]
Same here

- Version 0.4.45-7637265 (0.4.45-7637265)

**Comment by amig** [comment]
Same here (Gmail). I started typing a reply on my mobile phone and opened N1 to finish and send it. Drafts from Gmail started to accumulate with no control. I had to quit N1, go to gmail and delete all the drafts.

All drafts where from the point I stopped editing on the phone.

**Comment by xclabit** [comment]
This has always been an ongoing problem for me with my work mail (IMAP configuration) ever since I started using N1 3 or 4 months ago.

I use N1 at home on my Windows machine and the Mail.app on my Mac at work. After a day of work, I come home and noticed N1 has hundreds of drafts each one an incremental version of the final e-mail I send out from work. One time I had 500+ drafts for a single reply. It slowed N1 down tremendously. I check my Mail.app at work again and now I see those 500+ drafts. Fortunately, Mail.app was unfazed by this and I was able to mass delete those drafts without a problem.

- IMAP/SMTP
- Not on my home machine right now but I updated the Windows N1 client a few days ago
- Running via Nylas Pro account (1-year free trial)

Another issue I've noticed is that the e-mail I've sent from N1 do not appear in the IMAP Sent Folder, although I do see it in the message thread from Mail.app.

**Comment by emorikawa** [comment]
This appears to happen for drafts that are started from not N1, or edited outside of N1. We are looking into why this is happening now.

**Comment by emorikawa** [comment]
An additional report from Nylas Support: https://nylas.zendesk.com/agent/tickets/4247

**Comment by emorikawa** [comment]
An additional report from Nylas support: https://nylas.zendesk.com/agent/tickets/4216

**Comment by jackiehluo** [comment]
Another incidence: https://twitter.com/cycomachead/status/748735237539045376

**Comment by jackiehluo** [comment]
Two more incidences:
https://nylas-chat.slack.com/archives/n1-help/p1467388227000624
https://nylas-chat.slack.com/archives/n1-help/p1467389745000626

**Comment by xclabit** [comment]
As an additional update, I can consistently replicate this problem when I left N1 opened on my machine at home and I try to write a draft using Mail.app from work. Drafts (incremental edits of the email I've sent out) are constantly downloading onto my Mail.app client as I'm typing this (35+ and counting).

I also distinctly remember not seeing any of these drafts created if I made sure to close out of N1 at home before I head to work.

**Comment by jackiehluo** [comment]
Another incidence: https://nylas-chat.slack.com/archives/n1-help/p1467776114000663

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4034

**Comment by grinich** [comment]
Another incidence: https://twitter.com/jacobhartog/status/751194986914340864

**Comment by emorikawa** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4480 @xclabit Thank you for confirming that. We're pretty sure it's related to drafts created outside of N1 and are tracking down a fix for this.

**Comment by skifaster** [comment]
+1 - having the same problem here...

**Comment by molstrangler** [comment]
+1 same here

**Comment by pamo** [comment]
🔂 same

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3948

**Comment by flaturtha** [comment]
I had the same problem yesterday (7/12/16). I started writing an email on my iPad, then saved the draft and finished writing it on N1. Was getting massive duplication in N1. I had to go back to my iPad, delete all the drafts that had been created (thankfully it is easy to do and actually dump the trash from iPad). The continuing problem is that now that email conversation/string, which only has 16 actual back-and-forth emails, says there are 78 in the string. Annoying trying to find the last email so I can get the links & reply.

**Comment by HarrisonB** [comment]
I've experienced this a few times, and yes I believe it has to do with editing drafts outside of Nylas.

**Comment by jstejada** [comment]
Another incidence in zendesk

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!

**Comment by xclabit** [comment]
Unfortunately, the problem appears again. Not as bad as before. Instead of hundreds of drafts, I see about 20 or so.

The funny thing is that I tried to force this problem to happen again as soon as I got the update (when it came out) and I wasn't able to re-duplicate the problem until today.

**Comment by xclabit** [comment]
Any update on this? It is still happening.

**Comment by Skilgarriff** [comment]
I just had this happen this morning. Once I canceled a message that was to be sent in the future, I now have over 100+ drafts and cannot open N1 without my computer coming to a standstill.

**Comment by xclabit** [comment]
As mentioned in my previous replies (Oct 21, Aug 23), this is still happening to me. It's pretty much a deal breaker.

**Comment by danielbayley** [comment]
> and cannot open N1 without my computer coming to a standstill.

I'm getting the same behaviour… I don't think this has been resolved.

> It's pretty much a deal breaker.

Agreed 😞

**Comment by Laul** [comment]
+1... 
Not hundred of drafts, but "only" 9.
I thought it would disappear after sending the e-mail, but it didn't. 

Note that the e-mail list in the google web app is hopefully okay (i.e., as expected I see the initial message and my answer, which is the e-mail subject to copies in Nylas). According to me it's quite a good news since it suggests a sync problem rather than a real copy... or at least I hope that !

**Comment by grinich** [comment]
What version of Nylas Mail are you running?


________________________________

**Comment by Laul** [comment]
Sorry for missing this info ; v. 1.0.11
          
            
            On janv. 24 2017, at 11:57 pm, Michael Grinich <notifications@github.com> wrote:
            
            
              What version of Nylas Mail are you running?


________________________________

**Comment by James9074** [comment]
Same issue here, seems like the drafts are being generated every time I enter text and pause for a short time, or sometimes on a regular interval regardless of what I'm doing (as long as the N1 client is open and in an active email draft). This is happening when working out of my gmail inbox (I have no other providers configured). I am running 1.0.11 as well.

**Comment by Laul** [comment]
Hi!
Just to tell that I upgraded yesterday and I still have the same issue. New
version installed is 1.0.12
Thanks !

2017-01-27 14:24 GMT-05:00 James Thomas <notifications@github.com>:
