### ISSUE TITLE
Mails i sent to myself won't show (yeah, i know..._

### ISSUE THREAD

**Issue by argamanza** [nylas/N1#2456]
##### Are there any related issues?

Not that i can find

##### What operating system are you using?
Windows 10 / Manjaro Linux

##### What version of N1 are you using?
Latest 0.4.45-7637265

--

**Bug?**
##### Do you have any third-party plugins installed?
I do (Emoji and Unsuscribe but it happens without them as well)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I tested it only with Gmail and Google apps emails so for now i'd say yes, for Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Reproducible with any message

--

I know it sounds weird, but emails i'm sending to myself won't show, it happens only when i send them with Nylas N1.

It started when i tried to test the new encryption system, i sent a mail to myself and didn't receive it.
I tried for a couple of time and than i guessed there's some issue with Gmail, so i sent a mail to a friend's mail account and he received it right away.

I'm using N1 for two accounts, one is a normal Gmail account and the other a student mail @ Google Apps.

When i send from one account to the other i receive it perfectly fine and fast, but when i send a mail to myself **from** and **to** the same account i won't receive it, and if i'll login to Gmail using the browser sometimes no email message at all,but i had one time when it was in "All Mail" as unread but not in the inbox.

I know that's not the most important issue in the world, but i guess a lot of people email to themselves as a test measure or whatever...

**Comment by Omeryl** [comment]
Hey,

I can't seem to reproduce this locally, I'm sending emails to myself, from myself, from both a Gmail and Google Apps account without error. Are you sure that the email in "All Mail" wasn't a draft?

**Comment by argamanza** [comment]
@Omeryl i'm sure, today i tested it again and two times in a row i received they messages right away, and thought the issue is solved, but once again (as you can see in the attached GIF) i'm sending a mail to myself and it never arrives at my inbox (both nylas and web Gmail).

![issue GIF](https://cloud.githubusercontent.com/assets/9576019/16133220/5e17f810-341f-11e6-82d5-1140db7e3561.gif)

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/5795

**Comment by grinich** [comment]
Could this just be delayed?

**Comment by duchere** [comment]
I can't believe this is not solved since August 2016. I don't think I'm the only perso to rapidly send an email to myself not to forget something.

**Comment by ArchangeGabriel** [comment]
Just to be clear here: does the mail appear in your “Sent Mail” boxes? If yes, then there is no Nylas issue here: [Google is discarding mails that already exists in your account at reception time](https://productforums.google.com/forum/#!topic/gmail/fkbKPajx1Dw) (based on Message-ID if I recall correctly), which includes all emails sent by you and to be received by you (either explicitly as in the case of this thread, or for when writing to subscribed mailing list as in the link above).

**Comment by duchere** [comment]
Hi, 

Yes it does appear in “sent mail”

But, why does it behave differently when I’m sending an email to myself via Gmail directly ? When I use Gmail, I have the mail sent to myself both in Inbox and in Sent mail.

I’m expecting the same behavior when I use Gmail directly or Nylas. And so most users are I guess.

Best, 

Jean

**Comment by ArchangeGabriel** [comment]
Because GMail, in its web interface, shows all mails (including sent ones) in the Inbox conversations threads when applicable (i.e. when you have any reply in the same thread or you sent an email which was to be delivered to you). In the case of an e-mail sent to yourself, it decides to show it in Inbox, even if its true location is in Sent Mail. If you delete either of them (Inbox or Sent Mail), the other one is going to trash too.

Thunderbird seems to support this by default by showing email sent to yourself directly in the Inbox for Gmail accounts. Not sure how they implemented it, but you can definitively see it’s the same email: they aren’t even any headers added to it. In K-9 Mail though, I received it with headers added, so there might be an issue with Message-ID not generated or something like that.

Probably needs a bit more investigation, but in all cases this is a GMail specific issue.

**Comment by yongk802** [comment]
This is still happening. I'm using Ubuntu 17.04. I've sent from my yahoo, gmail and outlook365 accounts to each of the accounts. None of the emails show up in any inboxes or in my sent folder. Definitely a bug and easy to reproduce.

**Comment by mattslay** [comment]
Yep, same problem still happening for me as of Nov 8, 2017.  This is BAD. I email stuff to myself all the time. Please fix this issue.

**Comment by Omeryl** [comment]
@mattslay Nylas Mail is dead. https://www.nylas.com/blog/sunsetting-nylas-mail-development

You'll want to move on to projects that forked Nylas Mail like:
https://getmailspring.com/

**Comment by mattslay** [comment]
Indeed Mailspring has already fixed this issue! Thanks for pointing me to it.
