### ISSUE TITLE
Buttons in dark theme need more contrast

### ISSUE THREAD

**Issue by dmvaldman** [nylas/N1#3]
Text is very hard to read.

**Comment by dillonforrest** [comment]
Yikes, you're right!

**Comment by hemanth** [comment]
![screen shot 2015-10-07 at 11 44 51](https://cloud.githubusercontent.com/assets/18315/10330289/de206974-6ce8-11e5-8fda-13ef4c90fa7f.png)

**Comment by emorikawa** [comment]
Yes! Fixed in 8755786

**Comment by hemanth** [comment]
:+1:

**Comment by chibipirate** [comment]
<img width="1272" alt="screen shot 2015-10-10 at 5 39 54 pm" src="https://cloud.githubusercontent.com/assets/12485020/10414046/003585a0-6f76-11e5-8ccb-1be429c16845.png">

@emorikawa Has this update been released? I'm on 0.315-14c5160 and it still does not look right.
