### ISSUE TITLE
Can't connect custom IMAP account -- stuck at the "Connect an Email Account" screen.

### ISSUE THREAD

**Issue by caldwell** [nylas/N1#3185]
I'm trying Nylas for the first time (Mac OS X 10.12) and when I get to the "Connect an Email Account" screen I can't proceed. I want to use a custom IMAP server so I select the "Add Custom IMAP Account…" menu item from the "Nylas Mail" menu but nothing happens. I don't have an account on any of the listed email providers so I can't get past the screen to see if the "Add Custom IMAP Account" works later.

**Comment by pngised** [comment]
Hi.
I update N1 to the new client version Nylas Mail, removing the old client.
I'm now unable to see anything other than the "Connect an email account".
I connected and authorized my Gmails accounts and nothing happened.

I'm stuck on the same "Connect an email account" screen.

**Comment by surdaft** [comment]
+1

Mac OS - 10.11.6
Nylas mail - 1.0.8 - Free plan

**Comment by roibeart** [comment]
Same problem here, I suspect that the possibility to configure custom IMAP accounts is not expected for now. Can anyone confirm this?

**Comment by yannick-mamudo** [comment]
#3179 probably related to this issue

**Comment by EQuimper** [comment]
+ 1

**Comment by jstejada** [comment]
Hi all, thanks for reporting! We're releasing a new version today that should fix an issue that made the app freeze (https://github.com/nylas/N1/commit/3e85aa4056adf5622d5f524ba4c35865ed940607).

We've also pushed some auth improvements. Let me know if youa re still having issues authenticating! Thanks!

**Comment by jstejada** [comment]
@caldwell, @pngised, @surdaft   We've released v 1.0.11-- let me know if you continue having issues!

**Comment by EQuimper** [comment]
@jstejada I got again the error after update

**Comment by caldwell** [comment]
v1.0.11 doesn't address the issue.

It's not that the app is freezing, it's just that the Add Custom IMAP Account…" menu doesn't do anything. The rest of the app still responds. I can click on the different email providers in the window and they take me to the page to sign in with one of them.

It's just that I don't have any accounts with any of the providers shown, so I can't proceed that way, and the since the custom IMAP menu doesn't work, I can't get my account added.

Is there some way to skip the onboarding and just jump into the app with no accounts? Maybe there it will let me add my custom IMAP account…

**Comment by amicablewings** [comment]
Still fails to connect with any email provider. (Version 1.0.11)

Error:
We were unable to reach your mail provider. Please try again.

**Comment by jstejada** [comment]
hi @amicablewings thanks for the report. I think the issue you are seeing is #3179

I'm going to rename this issue to specify that it is specific to custom IMAP accounts. Is anyone seeing this issue with a non-custom IMAP account?

**Comment by jstejada** [comment]
this should be fixed with https://github.com/nylas/N1/commit/23903178a4c41a8a351b239f05bcc3e1be7dd3ed

we will release this fix within the next few days!

**Comment by jstejada** [comment]
this fix has been released!

**Comment by EQuimper** [comment]
I can confirm that work thank you @jstejada

**Comment by caldwell** [comment]
Thanks, that fixed it!
