### ISSUE TITLE
Unread counts are incorrect for labels / folders

### ISSUE THREAD

**Issue by MrSassyBritches** [nylas/N1#489]
The unread badge always shows "1" even when I have no unread messages, can't get it to go away.

![capturen1](https://cloud.githubusercontent.com/assets/7945291/11432029/74b85040-9462-11e5-970f-c56ccecf25c5.PNG)

**Comment by jstejada** [comment]
hi @MrSassyBritches , thanks for reporting this! Have you updated to the latest version? This issue should be resolved with version 0.3.25.

**Comment by dkouvdis** [comment]
Same problem too. I searched `label:unread` on Gmail and found nothing

![screen shot 2015-11-29 at 17 08 01](https://cloud.githubusercontent.com/assets/2727196/11458623/c7705e76-96bb-11e5-807b-738709633e14.png)

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this. We introduced new optimizations in 0.3.25 that avoid re-calculating counts all the time, but it looks like they're causing these issues. I'll see if we can get it fixed soon.

**Comment by bengotow** [comment]
Merging in #140

**Comment by framerate** [comment]
I see this is closed, yet I'm still experiencing it. Is it in an upcoming release?

**Comment by colindevs** [comment]
@framerate same here

**Comment by colindevs** [comment]
### I am on 0.3.29, still experiencing the same problem.
![screen shot 2015-12-12 at 6 33 59 pm](https://cloud.githubusercontent.com/assets/12850952/11764458/3d5631ae-a0ff-11e5-9bba-21f44b1af296.png)
*In Nylas, shows 1 unread:*
![screen shot 2015-12-12 at 6 34 54 pm](https://cloud.githubusercontent.com/assets/12850952/11764462/51b610a6-a0ff-11e5-9c33-31b321e52228.png)
**And..**
![screen shot 2015-12-12 at 6 40 04 pm](https://cloud.githubusercontent.com/assets/12850952/11764476/d1ba0fd2-a0ff-11e5-8eb8-c761a8dd86b1.png)


*But in gmail web client it shows no unread messages:*
![screen shot 2015-12-12 at 6 35 29 pm](https://cloud.githubusercontent.com/assets/12850952/11764466/7163ca10-a0ff-11e5-8bc5-31b04a92e22a.png)
**And...**
![screen shot 2015-12-12 at 6 39 00 pm](https://cloud.githubusercontent.com/assets/12850952/11764474/b52b24f0-a0ff-11e5-8ef2-fda42f9cd030.png)

:pray: Hope someone can fix this soon :wrench:!

**Comment by dkouvdis** [comment]
Can you search in Gmail by `label:unread` if you have some unread emails.

**Comment by framerate** [comment]
I definitely have some unread but nothing in my inbox

**Comment by colindevs** [comment]
Yeah, and it returned a bunch of emails that I archived and are not in my inbox. But Nylas says I have one unread in my inbox.

**Comment by grinich** [comment]
With no actual unread messages in the N1 thread list?

**Comment by colindevs** [comment]
What do you mean by N1 thread list? As far as scrolling through the "Inbox" mailbox, no there are no unread messages.

**Comment by dkouvdis** [comment]
It happened to me once when an unread email are in the bin with `inbox` tag. Have a look

**Comment by colindevs** [comment]
@dkouvdis yes! I think. I searched is:unread label:inbox and got a hit, though it was all very confusing. But thanks a lot for the solution, I just wish there was an easier way to resolve this. Maybe only count unread that are actually in the inbox instead of with the inbox label, but I don't know. Thanks again!

**Comment by grinich** [comment]
How can it be in the Inbox without the inbox label? That sounds like a bug somehow?

**Comment by colindevs** [comment]
That's what I said.

**Comment by jstejada** [comment]
merging into #704

**Comment by jstejada** [comment]
issue for reference: #759
