### ISSUE TITLE
Search doesn't find emails, even when listed in suggestions dropdown

### ISSUE THREAD

**Issue by Bugsbane** [nylas/N1#571]
Hi there,
I just downloaded and installed n1 on Ubuntu 15.10 with the Plasma (KDE) desktop. After adding an imap email account and having to wait quite a while for the inbox results to show up, I noticed something strange about search.

Basically no search results ever show up.

This happens despite the dropdown suggestions, when you're typing in the search bar, clearly finding results, and threads with the phrase in the content body. I also made sure I searched for emails that were plain text, to ensure it wasn't some HTML email issue, but it wasn't.

![nylas](https://cloud.githubusercontent.com/assets/401733/11596797/54b34a2e-9a85-11e5-8039-a1ae549b6820.png)

hit enter, and I just get "No threads were found to display"

The log file is empty and CLI doesn't show anything.

n1 version 0.3.26-c1ce330 (I wish you'd put this info somewhere it could actually be copied, like in the help window...)

Ubuntu 15.10 with the Plasma / KDE workspace.

**Comment by bengotow** [comment]
Hi @Bugsbane — unfortunately, N1 maps through to your underlying mail provider's search (usually IMAP) to execute the search query. For some reason, that is returning no results even for the exact subject phrase. Can you try searching for only the first 10-20 characters of the email subject and let me know fi that changes the results?

We'll implement our own full search eventually, but for now we're tied to whatever search results Exchange / Gmail / IMAP can provide.

**Comment by Bugsbane** [comment]
No, I get no search results at all under any circumstances that I've tried, including:
* Searching for one word
* Searching for the first 10-20 characters
* Clicking on the thread in the search suggestion dropdown

**Comment by enoversum** [comment]
Can confirm, despite having suggestions right in the list below the search box when typing in a single word as a search term, absolutely no search results are found for whatever search term I use. Using another e-mail client I am able to find just what I need, both from local cache and the slower IMAP search (slow, but working).

**Comment by bengotow** [comment]
Hey folks, I /think/ this has been fixed in 92b3e6777bb245a143faa117ebfcb70e9a5eabba. Looks like we weren't URL encoding the query string, so queries with foreign characters and some punctuation were breaking the search. There may be other issues if even basic searches aren't working for you, though...

**Comment by bengotow** [comment]
Feel free to re-open if this is still an issue in the next release!

**Comment by seppentoni** [comment]
Same for me. I have a email with the subject "Reboot". The term "Reboot" is then suggested by the search but then it says "No threads found".

Im running on ```(0.3.27-1c2a936)```

**Comment by pioneerskies** [comment]
I can confirm the search is absolutely not working even in 0.4.5-b0ec335.
I simply believe relaying on IMAP search is a no-no for both functionality and speed.

Is internal search somewhat milestone-d/prioritized?

**Comment by Bugsbane** [comment]
Still getting this issue in 0.4.5-b0ec335 even when searching for just a word comprised only of letters, and the search suggestion returns an email title made up only of letters and spaces.

**Comment by lmartins** [comment]
Same here, no results no matter what I try.

**Comment by Bugsbane** [comment]
Just updated two days ago. Issue persists.

**Comment by jstejada** [comment]
Hi everyone, there was 3 separate issue for this so I'm merging into a single one: #750

**Comment by circuitfive** [comment]
Search is not returning all results. It seems like it's returning recent conversations, but nothing more than a few months old.

`Version 0.4.32-1de17e7 (0.4.32-1de17e7)`

For me, "success" means that N1 shows me the exact same results that I get when I do an identical search via Gmail or Google Inbox. Right now it's not even close.

**Comment by cpescott** [comment]
Same as @circuitfive - search not returning full results (only goes a couple months back).

**Comment by plzh** [comment]
Hi @bengotow, very disappointed to see such seriously issues are closed without truly been fixed.
