### ISSUE TITLE
Older Gmail accounts main folders prefixed with [Google Mail]

### ISSUE THREAD

**Issue by axllent** [nylas/N1#617]
I have three different accounts set up with N1. Two of them have the `Sent Mail`, `All Mail`, `Spam` & `Bin` all prefixed with `[Google Mail]/`, ie:

- Inbox
- Starred
- [Google Mail]/Sent Mail
- [Google Mail]/All Mail
- [Google Mail]/Spam
- [Google Mail]/Bin
- Drafts

The third simply says (as I assume they all should be):

- Inbox
- Starred
- Sent Mail
- All Mail
- Spam
- Bin
- Drafts

The difference between the first two and the last is that the first two have `[Google Mail]` as the parent folder of the main sections in the IMAP subscriptions, whereas the last has them simply as `[Gmail]`. I assume this is some legacy thing on Google's side as the first two accounts date back a lot longer than the last.

**Comment by rnarian** [comment]
Just ran into the same issue. 

I also think this is related to the age of the accounts. The one showing the issue is much older and initially used the @googlemail.com domain before they'd let you switch to @gmail.com. 

![bildschirmfoto 2015-12-08 um 10 27 19](https://cloud.githubusercontent.com/assets/1174951/11652140/4c5b1b68-9d96-11e5-9f37-402c1726ed07.png)
![bildschirmfoto 2015-12-08 um 10 27 07](https://cloud.githubusercontent.com/assets/1174951/11652141/4c5b467e-9d96-11e5-968c-ed1ef47fce05.png)

**Comment by sanderploegsma** [comment]
Me too, although I never had a @googlemail.com address, just gmail.

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this. I'll see if we can get this fixed in the sync-engine.

**Comment by frdmn** [comment]
+1

**Comment by kav-ya** [comment]
Thanks for the report folks!
This has been fixed in the sync-engine (commit 7cce697).

**Comment by rnarian** [comment]
Unfortunately this doesn't seem to work. I still got the `[Google Mail]` prefixed folders on one of my accounts. I tried to remove the account and add it again without success. Is there anything I'm missing?

**Comment by axllent** [comment]
I haven't noticed any change either, even after yesterday's upgrade of N1 to v0.3.36 (which I thought may be required to see the changes in the latest sync-engine).

**Comment by sanderploegsma** [comment]
@kav-ya Are we supposed to wait for the next client update or is it a back-end fix? Either way, running the latest version and still having the issue.

**Comment by nicoknoll** [comment]
Still not working...
