### ISSUE TITLE
Unable to send or reply to emails

### ISSUE THREAD

**Issue by mfid** [nylas/N1#893]
Version 0.3.34-dffc307
OS X 10.10.5
Office 365 account with Exchange

Was working fine until I updated to the latest beta. Now whenever I try to send an email or reply to an existing one nothing happens - the compose window remains open. I can see the emails in the Draft folder, but they're not being sent. No error message either.

Have tried reloading the app, hard quitting and restarting, no joy.

**Comment by denialprintco** [comment]
same issue on gmail .  mail will not send can not save draft. However i can see the draft on gmails site and in drafts folder.

**Comment by jstejada** [comment]
hi everyone, thanks for reporting this. Could you send the app logs by selecting `Developer` -> `Toggle Developer Tools` and selecting the `Console` tab?

**Comment by denialprintco** [comment]
/Applications/Nylas
N1.app/Contents/Resources/app.asar/src/error-logger.js:118 Streaming log
data to
/var/folders/rv/r1z7v2xj3x1526xcwnx3m1lc0000gn/T/Nylas-N1-463.466.log
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:717
EACCES: permission denied, mkdir '/usr/local/bin'
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:722
EACCES: permission denied, mkdir '/usr/local/bin'
index.js:11 Window load time: 1582ms
/Applications/Nylas
N1.app/Contents/Resources/app.asar/src/window-event-handler.js:330  Welcome
to N1! If you're exploring the source or building a plugin, you should
enable debug flags. It's slower, but gives you better exceptions, the debug
version of React, and more. Choose  Developer > Run with Debug Flags  from
the menu. Also, check out https://nylas.com/N1/docs for documentation and
sample code!
/Applications/Nylas
N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:328
 124msec: SELECT COUNT(*) as count FROM `Thread` INNER JOIN `Thread-Label`
AS `M8` ON `M8`.`id` = `Thread`.`id` WHERE `Thread`.`account_id` =
'20yhawr6olbfp4q8jyekpbnln' AND `M8`.`value` = '1wwsttbe1kiu6mictfy1c7761'
/Applications/Nylas
N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:328
 261msec: SELECT `Contact`.`data` FROM `Contact`  WHERE
`Contact`.`account_id` = '20yhawr6olbfp4q8jyekpbnln'
2/Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/email-fra…:78
Refused to load the stylesheet 'cid:emailsvc.css' because it violates the
following Content Security Policy directive: "style-src 'self'
'unsafe-inline'".
EmailFrame._writeContent @ /Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/email-fra…:78
/Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/email-fra…:78
The key "text/html;" is not recognized and ignored.
/Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/email-fra…:78
Error parsing a meta element's content: ';' is not a valid key-value pair
separator. Please use ',' instead.
file:///Users/Majette/.nylas/downloads/1mhieqf3wjycp9sisjxosvc2u/IMG_0311.JPG
Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by jstejada** [comment]
thanks @denialprintco , do you have any plugins installed? @mfid

**Comment by denialprintco** [comment]
no . no plugins.

**Comment by mfid** [comment]
Only plugin I have is QuickSchedule but I've disabled that to see if it made a difference, and nothing.

What is odd, is that I enabled Dev Tools, then reloaded the app, and now it's working...

**Comment by jstejada** [comment]
ok, thanks!

**Comment by denialprintco** [comment]
still not working for me.   :(

**Comment by samueldmcdermott** [comment]
I seem to be able to send some, but have a failure with some replies. The program seems to be stuck on a "sending draft..." status for a while, then fails with a message like "message could not be saved to drafts" -- even though I am trying to just send it directly. But sometimes it works after a second or third try. 

Perhaps related, a message seems to be "stuck" in my drafts, even though I have tried deleting it several times. It does not show up in my actual Gmail draft folder online.

**Comment by denialprintco** [comment]
all the message are showing up in my gmail folder online as well as in my
drafts folder in multiples actually.  the same message will have multiple
drafts saved.  even after i delete them it cant resend.

**Comment by jstejada** [comment]
@samueldmcdermott what version are you running?
if you are running the beta and have any plugins installed like @mfid , this issue should be fixed in https://github.com/nylas/N1/commit/141b2e73c9b11db5da21e7ef2e6a906bac542ac4.

@denialprintco I'm looking into your issue

**Comment by bengotow** [comment]
Hey folks—this should be fixed in the latest beta (`0.3.35`) - sorry for the hassle, lots of things being updated over the new year.

**Comment by denialprintco** [comment]
test reply.   ?!?!?!?!?!

> On Jan 4 2016, at 3:20 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

>

> Closed [#893](https://github.com/nylas/N1/issues/893).

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/893#event-505177232).![](https://github.com/notifications/beacon
/APxnANrzS3_V8s_VBZAe_EsRDoSlY1zRks5pWst0gaJpZM4G-A5u.gif)

**Comment by denialprintco** [comment]
yes its working now thank you

**Comment by samueldmcdermott** [comment]
Agreed, thanks for your work and your nice product!

> On Jan 4 2016, at 3:24 pm, denialprintco &lt;notifications@github.com&gt;
wrote:  

>

> yes its working now thank you

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/893#issuecomment-168793965).![](https://github.com/notifications/beac
on/AI09dN4jtrl263Ftt36cSTqiVnNmLLiuks5pWsyCgaJpZM4G-A5u.gif)

**Comment by robertcerny** [comment]
Hi,
what's the latest beta version which should work with iCloud? My Nylas Mail just downloaded version 1.0.11 and it still doesn't work.
